### ISSUE TITLE
Extension Not Providing CSV

### ISSUE THREAD

**Issue by StephanBlack47** [NoWorries/chrome-figma-ui-mod#20]
Hi! Trying to download an analytics CSV via the extension, navigating to the https://www.figma.com/files/ analytics view, but no response from the 'Export Analytics as CSV' button. Please let me know what I can do to navigate this error!

Thanks!

**Comment by NoWorries** [comment]
Hi, is the button not triggering any messaging at  all?

Are you able to look at the Console on Developer Tools and see if there is a message displayed?

**Comment by StephanBlack47** [comment]
Hey, Thank you for the quick response! It took me a bit to figure out, but finally solved the issue. As you may know, there are two flows to get to the library analytics view. The first path was where I ran into the issue downloading but the second path allowed me to download the csv. 

First path: All workspaces > Libraries > 'select' library > tab over to Analytics > trigger extension > No response from extension

Successful Path: Open project > 'right-click' Library > 'select' Library Analytics > tab over to Analytics > Trigger extension > Success!! 

It ultimately brings you to the same view, but the URL for the successful path has more content.

Otherwise this tool is amazing and I really appreciate it!!

**Comment by NoWorries** [comment]
Thanks for the explanation, glad you got it working!

I'll make an adjustment to the script so it should work from both paths.
