### ISSUE TITLE
Variable width option?

### ISSUE THREAD

**Issue by phennessey** [NoWorries/chrome-figma-ui-mod#22]
Your tool doubles the width of the side panel, but this is actually a bit too big for me.

Would be great if your plugin had a variable width option.

**Comment by NoWorries** [comment]
Hiya, I initially put that in the "too hard" basket. I'll see if that's an option, the challenge was with sizing all the individual elements and their spacing. 

Doubling it was much easier than working out variable width.

If anyone is interested in contributing to this, more than welcome to help with improvements

**Comment by NoWorries** [comment]
Hi @phennessey, are you happy for me to close this after UI3 changes?

**Comment by phennessey** [comment]
I haven't tested your latest version yet! But yes, feel free to close if it's no longer relevant.
