### ISSUE TITLE
Columns B to E of the downloaded CSV are blank.

### ISSUE THREAD

**Issue by sh1m17u** [NoWorries/chrome-figma-ui-mod#23]
I opened the Analytics tab of the Figma Analytics modal and downloaded the CSV, but columns B to E are blank.
As of March 2, 2024, I was able to download files without any problems.

**Comment by NoWorries** [comment]
Hiya, I'll look into it. Assume they've adjusted some of the page elements that were being targeted. Thanks for flagging the issue!

**Comment by NoWorries** [comment]
Can you let me know the browser, how you opened the modal, and if you are aware of any component name changes that might be tripping up the save. 

I just did a test export and had no issues:, would really like to understand what is happening and fix it for you.
<img width="822" alt="image" src="https://github.com/NoWorries/chrome-figma-ui-mod/assets/803064/1ae467e7-deba-4725-93f8-86c2c5a4c459">

**Comment by sh1m17u** [comment]
Thank you for your support. I will share some information with you to solve this issue.

Browser: Google Chrome v.123.0.6312.59
How I opened the modal:
Click Library Analytics from the triangle to the right of the file name → Click Analytics Tab → Wait for the data to finish loading → Launch the extension and download CSV

**Comment by NoWorries** [comment]
Thanks for the info, yeah thats the same method I used and i'm testing with Chrome 123.0.6312.59  aswell.
Does the entire Column A in the modal get downloaded to the CSV or does it finish prematurely? Just wondering if there is a particular component name that is causing an issue with the script?

**Comment by sh1m17u** [comment]
The entire A column of the modal was downloaded.

**Comment by NoWorries** [comment]
Okay thanks for checking. I'm at a bit of a loss to understand the issue as i cant recreate it.

Just out of curiosity, does this bookmarklet version still work?
https://gist.github.com/NoWorries/5c1763d6ad2ec784366d23b0880ae666

**Comment by VamonosPest** [comment]
I ran into the same issue, tried the bookmarklet version and got the same results... 
<img width="574" alt="Capture d’écran 2024-03-27 à 13 13 13" src="https://github.com/NoWorries/chrome-figma-ui-mod/assets/1050194/cd7dc1bb-ac1f-4737-badd-31dfeb171f46">

**Comment by faisne** [comment]
Same for me.

**Comment by srice-godaddy** [comment]
PR for the fix is here: https://github.com/NoWorries/chrome-figma-ui-mod/pull/26

Verified working on my machine. (Chrome on OSX)

Might have to do with running in enterprise versus pro or org? Does the fixed version work for you still? (We're on an enterprise license)

**Comment by NoWorries** [comment]
Thanks @srice-godaddy for the PR, this has been merged into main and updated extension submitted for review in Chrome Web Store. 
Marking as closed.

**Comment by NoWorries** [comment]
Version 1.0.1 has now been published!
