### ISSUE TITLE
It doesn't export the numbers

### ISSUE THREAD

**Issue by Llanderal** [NoWorries/chrome-figma-ui-mod#25]
Hi, I am trying to use this chrome extension but it only exports the left hand column, it doesn't export the numbers. Any idea if I am doing anything wrong?

**Comment by VamonosPest** [comment]
I encountered the same issue!

**Comment by srice-godaddy** [comment]
I'm also running into this issue. My team is on the enterprise plan with multiple "workspaces". Not sure if that's related or not.

**Comment by srice-godaddy** [comment]
I wonder if it has to do with the last selector on this line. source code on my screen has only two dashes at the end, not 3. https://github.com/NoWorries/chrome-figma-ui-mod/blob/727d0af60ec5ab2ce1d32efe02261a5b5fd4a945/background.js#L27

**Comment by srice-godaddy** [comment]
PR for the fix is here: https://github.com/NoWorries/chrome-figma-ui-mod/pull/26

Verified working on my machine.

**Comment by NoWorries** [comment]
Thanks @srice-godaddy for the PR, this has been merged into main and updated extension submitted for review in Chrome Web Store. 
Marking as closed.

**Comment by NoWorries** [comment]
Version 1.0.1 has now been published
