### ISSUE TITLE
Export analytics not working for me

### ISSUE THREAD

**Issue by ghost** [NoWorries/chrome-figma-ui-mod#27]
Thanks for working on this, it is a much needed Figma feature.
Unfortunately when I click on "Export analytics as CSV" nothings happens.
I tried to review my browser configuration but it seems nothing is blocked for the extension.

**Comment by NoWorries** [comment]
Have you got the library analytics modal visible, and showing all the data, before pressing the button?

**Comment by NoWorries** [comment]
Will check asap and see if I can recreate issue. When Figma make changes to their underlying product page code it will interfere with the data export.

**Comment by ghost** [comment]
> Have you got the library analytics modal visible, and showing all the data, before pressing the button?

Yes it is visible and the toggle UI button works

<img width="1508" alt="image" src="https://github.com/NoWorries/chrome-figma-ui-mod/assets/56694561/9c378fec-c009-4fb3-bbd9-6721c842fced">

**Comment by NoWorries** [comment]
Just tested and can export the component analytics in our account. 
What Figma plan are you on?

<img width="801" alt="image" src="https://github.com/NoWorries/chrome-figma-ui-mod/assets/803064/e42aeb7d-4e5c-4aac-a3d4-a19f646f2c86">

**Comment by ghost** [comment]
We are on enterprise plan. I found a way to download without your extension, but it doesn't include components info.

**Comment by NoWorries** [comment]
Could I ask if you have tried again since, there was a patch contributed and I wonder if that will have helped you.

**Comment by ghost** [comment]
> Could I ask if you have tried again since, there was a patch contributed and I wonder if that will have helped you.

It's still not working for me, however Figma updated their API and now I can get the analytics from our library using it. Thanks anyhow!

**Comment by NoWorries** [comment]
Sorry it still isn't working, will investigate.
Great to hear you've got your results more directly though!

**Comment by NoWorries** [comment]
HI, just submitted a fix for CSV export. Changes in the URL after UI3 were the root cause. Let me know if this starts working when you get v1.0.2
