### ISSUE TITLE
Unable to export analytics

### ISSUE THREAD

**Issue by boucksy** [NoWorries/chrome-figma-ui-mod#30]
Hi Josh! I love your plugin, but unfortunately it hasn't been exporting any data for the last couple weeks.

Relevant info you may be interested in from similar, previous issues posted:
-  Our library names are are prefixed with "❖" (this has never been a problem before)
- Running the report on Chrome build 126.0.6478.183 (Official Build) (arm64)
- All of our data loads prior to attempting to export
- The console oddly doesn't give any feedback despite repeatedly hitting the button
- Attempts to export both with UI toggle on and off fail
- UI toggle continues to work
- No interfering third-party plugins enabled

Any ideas of what might be happening? This seemed to start at the beginning of July. Thank you!

**Comment by boucksy** [comment]
Update: I've had 2 other colleagues try to run the export as well and have failed to do so. So it does seem it isn't isolated to just my machine :(

**Comment by NoWorries** [comment]
Thanks for all the info @boucksy, i'll try and take a look this week for you. Probably just some IDs/ClassName changes under the hood after all the figma updates lately.

**Comment by NoWorries** [comment]
HI, just submitted a fix for CSV export. Changes in the URL after UI3 were the root cause. Let me know if this starts working when you get v1.0.2

**Comment by boucksy** [comment]
Thank you Josh! Ran it this morning without any issues, appreciate your work!

**Comment by NoWorries** [comment]
Great, glad it's working for you!
