### ISSUE TITLE
The CSV ca't be downloaded

### ISSUE THREAD

**Issue by mkhalil8x8** [NoWorries/chrome-figma-ui-mod#31]
I followed all the steps but the button doesn't work to download the csv.

**Comment by mvarts** [comment]
the same

**Comment by NoWorries** [comment]
Hello, thanks for posting an issue. I have just submitted a new version which is exporting again successfully.

Issue: The Figma UI3 code changes broke the export pattern matching, this has been resolved in v1.03.
