### ISSUE TITLE
when trying to export analytics nothing happens

### ISSUE THREAD

**Issue by mvarts** [NoWorries/chrome-figma-ui-mod#32]

**Comment by NoWorries** [comment]
Hello, thanks for posting an issue. I have just submitted a new version which is exporting again successfully.

Issue: The Figma UI3 code changes broke the export pattern matching, this has been resolved in v1.03.

**Comment by NoWorries** [comment]
Submitted a new version, they usually don't take long to be reviewed. Look for version 1.1.0 and let me know how you get on?

**Comment by NoWorries** [comment]
v1.1.0 is now available, please let me know if this does/doesn't work for you.

https://chromewebstore.google.com/detail/figma-ui-mod/pakkdlcbmijjkcocojcgonopnbkeolle
