### ISSUE TITLE
'Library Analytics modal is not visible' error 

### ISSUE THREAD

**Issue by jchourdeaux** [NoWorries/chrome-figma-ui-mod#33]
Hi, 
hope you're doing well.

When clicking on the 'Export Analytics as CSV' button, with the Analytics modal opened on the page, i've got a prompt with the message 'Library Analytics modal is not visible' 

I am missing something or is there a workaround ? 

<img width="500" alt="Screenshot 2024-09-25 at 11 24 16" src="https://github.com/user-attachments/assets/3b6be469-4033-4aa2-b5c9-9431d72c5b7f">

Thanx for your help. 
Kind regards

**Comment by NoWorries** [comment]
Thanks for the screenshot, there definitely is an issue here.
I see you have launched it from outside the file, that must be using some slightly different naming conventions in the code. 

I'll investigate and let you know

**Comment by NoWorries** [comment]
Submitted a new version, they usually don't take long to be reviewed. Look for version 1.1.0 and let me know how you get on?

**Comment by NoWorries** [comment]
v1.1.0 is now available, please let me know if this does/doesn't work for you.

https://chromewebstore.google.com/detail/figma-ui-mod/pakkdlcbmijjkcocojcgonopnbkeolle

**Comment by jchourdeaux** [comment]
Hi @NoWorries, 
it works, thanx for the fix!
kind regards
JC
