### ISSUE TITLE
After the latest Figma update, export to file stopped working again

### ISSUE THREAD

**Issue by mvarts** [NoWorries/chrome-figma-ui-mod#34]
After the latest Figma update, export to file stopped working again

**Comment by NoWorries** [comment]
Hi sorry didn't reply sooner, working on a fix. Partially solved 😁

**Comment by NoWorries** [comment]
Submitted a new version, they usually don't take long to be reviewed. Look for version 1.1.0 and let me know how you get on?

**Comment by NoWorries** [comment]
v1.1.0 is now available, please let me know if this does/doesn't work for you.

https://chromewebstore.google.com/detail/figma-ui-mod/pakkdlcbmijjkcocojcgonopnbkeolle

**Comment by NoWorries** [comment]
Closing old ticket
